baseurl: "/"
title: Samet Demir
description: "PhD Candidate in Computer Science and Engineering at Koç University - KUIS AI Center"

twitter_username: simitii
github_username: simitii
linkedin_username: simitii

social:
  name: Samet Demir
  links:
    - https://twitter.com/simitii
    - https://www.linkedin.com/in/simitii
    - https://github.com/simitii

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
